;PERIFÉRICOS
BTN_ON_OFF EQU 030AH ;ENDEREÇO DO PERIFERICO DO USERNAME
SEL_NR_MENU EQU 0349H ;ENDEREÇO DO PERIFERICO DA PASSWORD
BTN_OK EQU 035AH ;ENDEREÇO DO SELETOR NR_SEL
BTN_CHANGE EQU 1D0H ;ENDEREÇO DO BOTÃO OK
PESO EQU 3E0H; 
;CONSTANTES
PERIFERICOS EQU 0300H
CARACTERVAZIO EQU 20H ;ASCII 20H É O ESPAÇO
ESTADO EQU 0318H
OPCAO_ESQUERDA EQU 0349H
OPCAO_DIREITA EQU 034AH


;BASE DE DADOS
BASEDEDADOS EQU 7000H ;ENDEREÇO DE INICIO DA BASE DE DADOS
NUMCLIENTES EQU 10 ;NUMERO MAXIMO DE CLIENTES DA PIZZARIA
BD_USER EQU 0 ;INDICE DO USERNAME DENTRO DA FICHA DE CLIENTE
BD_PASS EQU 16 ;INDICE DA PASSWORD DENTRO DA FICHA DE CLIENTE
BD_VALOR EQU 32 ;INDICE DO VALOR DENTRO DA FICHA DE CLIENTE
TAM EQU 48 ;TAMANHO DE CADA FICHA DE CLIENTE

;DISPLAY
DISPLAY EQU 0380H ;ENDEREÇO ONDE COMEÇA E É APRESENTADO O DISPLAY
DISPLAYEND EQU 0480H ;ENDEREÇO ONDE ACABA O DISPLAY

;««««««««««««««««««««««««««««««««««««
;	MENUS DO PROJETO
;»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»
PLACE 1FC0H
ESTADO_DA_MAQUINA:
	STRING "BOTAO ON [ ]    "
	STRING "ESTADO [   ]    "
	STRING "                "
	STRING "                "
	STRING "OPCAO -->    	"
	STRING "  BOTAO OK [ ] 	"
	STRING "                "
TABLE 1
MENU_1:
	STRING "                "
	STRING "      MENU      "
	STRING "                "
	STRING "1-MODO BALANCA 	" 
	STRING "                "
	STRING "2-MODO DE VISUA_" 
	STRING "  LIZACAO TOTAL "
	STRING "                "
	STRING "3-RESET DO TOTAL" 
	STRING "  ACUMULADO 	"
	STRING "                "
TABLE 1
MENU_ALIMENTOS:
	STRING "                "
	STRING "   ALIMENTOS    "
	STRING "                "
	STRING "01->AVEIA       "
	STRING "02->PAO DE FORMA"
	STRING "03->BATATA      "
	STRING "04->ARROZ       "
	STRING "05->FEIJAO      "
	STRING "06->LEGUMES     "
	STRING "07->TOMATE      "
	STRING "08->BANANA      "
	STRING "09->LARANJA     "
	STRING "10->MACA        "
	STRING "11->KIWI        "
	STRING "12->BOLACHA CHOC"
	STRING "13->PIZZA Q&F PD"
	STRING "14->AMENDOAS    "
	STRING "15->LINHACA     "
	STRING "16->AZEITE      "
	STRING "17->LEITE MAGRO "
	STRING "18->WHEY        "
	STRING "20->SALMAO      "
	STRING "21->PESCADA     "
	STRING "22->ATUM        "
	STRING "23->PORCO       "
	STRING "24->FRANGO      "
	STRING "25->PERU        "
	STRING "26->OVO         "	
	STRING "27->QUEIJO      "
	STRING "                "
TABLE 1
MENUERRO:
	String "  ATENÇãO       "
	String "                "
	String "     OPÇÃO      "
	String "    ERRADA      "
	String "                "
	String "                "
	String "                "
	
Aveia:
	WORD 11
	WORD 56
	WORD 7
PAO_FORMA:
	WORD 9
	WORD 42
	WORD 3
BATATA:
	WORD 3
	WORD 19
	WORD 0

	
	
PLACE 0000H
INICIO:
	MOV R0, BTN_ON_OFF
	MOVB R0, [R0]	
	MOV R1, SEL_NR_MENU
	MOV R2, BTN_OK
	MOV R3, BTN_CHANGE
	MOV R4, PESO
	
	CALLF LIMPADISPLAY	
	CALLF MOSTRA_ESTADO
	
	;CALL LE_OPCAO
	JMP ATUALIZA

ATUALIZA:
	CALL ATUALIZA_BTN_ON_OFF
	CALL LER_BTN_OK
	JMP ATUALIZA
	
ATUALIZA_BTN_ON_OFF:
	PUSH R1
	MOV R1, BTN_ON_OFF
	MOVB R1, [R1]	
	CMP R1, R0
	JNE ON_OFF
	POP R1
	RET
ON_OFF:
	MOV R0, BTN_ON_OFF
	MOVB R0, [R0]
	POP R1
	PUSH R0
	PUSH R1
	MOV R0, BTN_ON_OFF
	MOVB R0, [R0]
	MOV R1, 58H
	CMP R0, R1
	JNZ OFF
	MOV R0, ESTADO
	MOV R1, 4FH
	MOV R2, 4EH
	MOVB [R0], R1
	ADD R0, 1
	MOVB [R0], R2
	ADD R0,1
	MOV R1, 20H
	MOVB [R0], R1
	POP R1
	POP R0
	MOV R5, MENU_1 ;METER UM CASE AQUI PARA OUTROS MENUS
	CALLF MOSTRADISPLAY
	RET
OFF:
	PUSH R0
	PUSH R1
	MOV R0, ESTADO
	MOV R1, 4FH
	MOVB [R0], R1
	ADD R0, 1
	MOV R1, 46H
	MOVB [R0], R1
	ADD R0, 1
	MOV R1, 46H
	MOVB [R0], R1
	MOV R0, BTN_ON_OFF
	MOV R1, 20H
	MOVB [R0], R1
	POP R1
	POP R0
	CALLF LIMPADISPLAY
	CALL ATUALIZA

MOSTRA_ESTADO:
	PUSH R0
	PUSH R1
	PUSH R2
	PUSH R3
	MOV R0, PERIFERICOS
	MOV R2, ESTADO_DA_MAQUINA
CICLO_ESTADO:
	MOVB R3, [R2]
	MOVB [R0], R3
	ADD R0, 1
	ADD R2, 1
	CMP R3, 0
	JNZ CICLO_ESTADO
	POP R3
	POP R2
	POP R1
	POP R0
	RETF

MOSTRADISPLAY:
	PUSH R0
	PUSH R1
	PUSH R3
	MOV R0, DISPLAY
	MOV R1, DISPLAYEND
CICLO_MOSTRA:
	MOVB R3, [R5]
	MOVB [R0], R3
	ADD R0, 1
	ADD R5, 1
	CMP R3, 0
	JNZ CICLO_MOSTRA
	POP R3
	POP R1
	POP R0
	RETF
	
LIMPADISPLAY:
	PUSH R0
	PUSH R1
	PUSH R2
	MOV R0, DISPLAY
	MOV R1, DISPLAYEND
	MOV R2, CARACTERVAZIO
CICLO_LIMPA:
	MOVB [R0], R2
	ADD R0, 1
	CMP R0, R1
	JLE CICLO_LIMPA
	POP R2
	POP R1
	POP R0
	RETF
	
LER_SEL_NR_MENU:
	PUSH R0
	PUSH R1
	PUSH R2
	PUSH R3
	PUSH R4

	CALL ENTRE_0_9
	
	POP R4
	POP R3
	POP R2
	POP R1
	POP R0
	RET

ENTRE_0_9:
	
	MOV R0, SEL_NR_MENU
	MOVB R0, [R0]
	MOV R1, 30H ;MINIMO-1
	MOV R2, 39H ;MAXIMO
	
	CMP R0,R1
	JLT ERRO_SEL_NR_MENU; R0 < R1
	CMP R0,R2
	JGT ERRO_SEL_NR_MENU; R0 > R2
	
	MOV R0, SEL_NR_MENU ;PROXIMO CHR
	ADD R0, 1
	MOVB R0, [R0]
	CMP R0,R1
	JLT ERRO_SEL_NR_MENU; R0 < R1
	CMP R0,R2
	JGT ERRO_SEL_NR_MENU; R0 > R2
	RET
ERRO_SEL_NR_MENU:
	PUSH R5
	MOV R5, MENUERRO
	CALLF LIMPADISPLAY
	CALLF MOSTRADISPLAY
	POP R5
	;MOV R5, MENU_1

	CALL LER_BTN_OK
	RET  

LER_BTN_OK:
	PUSH R0
	PUSH R1
	MOV R0, BTN_OK
	MOVB R0, [R0]
	MOV R1, 58H
	CMP R0, R1
	JNE LER_BTN_OK_FIM
	CALL LER_SEL_NR_MENU
	CALL LE_OPCAO
	MOV R1, CARACTERVAZIO
	MOV R0, BTN_OK
	MOVB [R0], R1
	POP R1
	POP	R0
	CALLF LIMPADISPLAY
	CALLF MOSTRADISPLAY
LER_BTN_OK_FIM:
	RET
	
LE_OPCAO:
	PUSH R0
	PUSH R1
	PUSH R2
	PUSH R3
	PUSH R4
	
	MOV R0, OPCAO_ESQUERDA
	MOVB R0, [R0]
	MOV R1, OPCAO_DIREITA
	MOVB R1, [R1]
	MOV R2, 30H
	
	SUB R0, R2
	SUB R1, R2
	
	MOV R4, MENU_1
	CMP R5, R4
	JEQ CASO_1
	
	MOV R4, MENU_ALIMENTOS
	CMP R5, R4
	JEQ CASO_2
	
	
	CASO_1:
		CMP R0, 0
		JNE CASO_2
		CMP R1, 1
		JNE CASO_2
		
		MOV R5, MENU_ALIMENTOS
		JMP LER_BTN_OK_FIM
	CASO_2:
		;AINDA N TEMOS MENU

	LE_OPCAO_FIM:
	POP R4
	POP R3
	POP R2
	POP R1
	POP R0
	RET


		

	


