;PERIFÉRICOS
BTN_ON_OFF 		  EQU 0B0AH ;ENDEREÇO DO PERIFERICO DO USERNAME
SEL_NR_MENU 	  EQU 0B49H ;ENDEREÇO DO PERIFERICO DA PASSWORD
BTN_OK 			  EQU 0B5AH ;ENDEREÇO DO SELETOR NR_SEL
BTN_CHANGE 		  EQU 0C0BH ;ENDEREÇO DO BOTÃO OK
BTN_GRAVAR 		  EQU 0C1BH
BTN_SIM			  EQU 0CC6H
BTN_NAO			  EQU 0CCCH
PESO 			  EQU 0BD7H;
;CONSTANTES
CARACTERVAZIO 	  EQU 20H ;ASCII 20H É O ESPAÇO
ESTADO 			  EQU 0B18H
ROTINA_ESQUERDA   EQU 0C49H
ROTINA_DIREITA 	  EQU 0C4AH




;INDICE

INDICE_PROXIMO 		EQU 2
INDICE_PROXIMO_NOME EQU 4
INDICE_PROXIMO_REG 	EQU 9


BD_NOME 	EQU 1EA0H
BD_PROTEINA EQU 1EB0H
BD_CARBONO  EQU 1EC0H
BD_GORDURA  EQU 1ED0H
BD_PESO  	EQU 1EE0H
BD_PESO_HEX EQU 1EF0H
BD_KCAL_SUM EQU 1F00H

KCAL_PROTEINA 	EQU 4
KCAL_CARBONO 	EQU 4
KCAL_GORDURA 	EQU 9

TOTAL_PROTEINA 	EQU 1F10H
TOTAL_CARBONO 	EQU 1F20H
TOTAL_GORDURA 	EQU 1F30H
TOTAL_KCAL_SUM 	EQU 1F40H


BASEDEDADOS EQU 7000H

;DISPLAY
PERIFERICOS EQU 0B00H
DISPLAY EQU 0B80H ;ENDEREÇO ONDE COMEÇA E É APRESENTADO O DISPLAY
DISPLAYEND EQU 0D70H ;ENDEREÇO ONDE ACABA O DISPLAY
DISPLAY_ALIMENTOS EQU 0BA1H

DISPLAY_NOME_GRAVAR 	EQU 0BB5H
DISPLAY_PESO_GRAVAR 	EQU 0BCBH
DISPLAY_PROTEINA_GRAVAR EQU 0BDBH
DISPLAY_HIDRATOS_GRAVAR EQU 0BEBH
DISPLAY_GORDURA_GRAVAR 	EQU 0BFBH
DISPLAY_KCAL_GRAVAR 	EQU 0C0BH

DISPLAY_PROTEINA_GRAVAR_TOTAL EQU 0C3BH
DISPLAY_HIDRATOS_GRAVAR_TOTAL EQU 0C4BH
DISPLAY_GORDURA_GRAVAR_TOTAL  EQU 0C5BH
DISPLAY_KCAL_GRAVAR_TOTAL 	  EQU 0C6BH

DISPLAY_PROTEINA_TOTAL 	EQU 0BABH
DISPLAY_HIDRATOS_TOTAL 	EQU 0BBBH
DISPLAY_GORDURA_TOTAL 	EQU 0BCBH
DISPLAY_KCAL_TOTAL 		EQU 0BDBH


;««««««««««««««««««««««««««««««««««««
;	PERIFERICOS
;»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»

PLACE 1FC0H
ESTADO_DA_MAQUINA:
	STRING "BOTAO ON [ ]    "
	STRING "ESTADO [   ]    "
	STRING "                "
	STRING "                "
	STRING "OPCAO -->    	"
	STRING "  BOTAO OK [ ] 	"
	STRING "                "
	
;««««««««««««««««««««««««««««««««««««
;	MENUS DO PROJETO
;»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»
	
TABLE 1
MENU_1:
	STRING "                "
	STRING "      MENU      "
	STRING "                "
	STRING "1-MODO BALANCA 	" 
	STRING "                "
	STRING "2-MODO DE VISUA_" 
	STRING "  LIZACAO TOTAL "
	STRING "                "
	STRING "3-RESET DO TOTAL" 
	STRING "  ACUMULADO 	"
	STRING "                "
	STRING "4-ADICIONAR     " 
	STRING "  ALIMENTOS 	"
	STRING "                "
TABLE 1
MENU_ADD_MENU:
	STRING "                "
	STRING " ADD ALIMENTOS  "
	STRING "NOME:           " 
	STRING "[              ]"
	STRING "                " 
	STRING "PROTEINA:       " 
	STRING "[              ]"
	STRING "                " 
	STRING "H_CARBONO:      " 
	STRING "[              ]"
	STRING "                "
	STRING "GORDURA:        " 
	STRING "[              ]"
	STRING "                "
	STRING "  GRAVAR  [ ]   "
	STRING "                " 
	STRING "                "
TABLE 1
PESAGEM:
	STRING "                "
	STRING "  : ALIMENTO :  "
	STRING "[              ]"
	STRING "                " 
	STRING "                "
	STRING " PESO [____] G  "
	STRING "                " 
	STRING "                "
	STRING "  CHANGE  [ ]   "
	STRING "  GRAVAR  [ ]   "
	STRING "                " 
	STRING "                "
TABLE 1
MENU_ALIMENTOS:
	STRING "                "
	STRING "   ALIMENTOS    "
	STRING "                "
TABLE 1
MENUERRO:
	STRING "    ATENCAO     "
	STRING "                "
	STRING "     OPCAO      "	
	STRING "     ERRADA     "
	STRING "                "
	STRING "  CLIQUE EM OK! "
	STRING "                "
TABLE 1
MENUERRO_PESAGEM:
	STRING "    ATENCAO     "
	STRING "                "
	STRING " #PESO INVALIDO "	
	STRING "                "
	STRING "  CLIQUE EM OK! "
	STRING "                "
TABLE 1
MENU_GRAVADO:
	STRING "   |ATENCAO|    "
	STRING "                "
	STRING "  GRAVADO COM   "	
	STRING "  SUDCESSO !!   "
	STRING "                "
	STRING "  CLIQUE EM OK! "
	STRING "                "
TABLE 1
MENU2_GRAVAR:
	STRING "ATENCAO|[GRAVAR]"
	STRING "                "
	STRING "[DADOS A GRAVAR]"
	STRING "NOME[__________]"
	STRING "PESO ---> [____]"
	STRING "PROTEINA|P[____]"
	STRING "HIDRATOS|C[____]"
	STRING "GORDURA |F[____]"
	STRING "KCAL |KCAL[____]"
	STRING "                "
	STRING "    [TOTAL]     "
	STRING "PROTEINA|P[____]"
	STRING "HIDRATOS|C[____]"
	STRING "GORDURA |F[____]"
	STRING "KCAL|TOTAL[____]"
	STRING "                "
	STRING "PRETENDE GRAVAR "	
	STRING "OS              "
	STRING "MACRONUTRIENTES?"
	STRING "                "
	STRING "  SIM[ ]NAO[ ]  "
	STRING "                "
	STRING "                "
TABLE 1
MENU_TOTAL:
	STRING "    [TOTAL]     "
	STRING "                "
	STRING "PROTEINA|P[____]"
	STRING "HIDRATOS|C[____]"
	STRING "GORDURA |F[____]"
	STRING "KCAL|TOTAL[____]"
	STRING "                "
	STRING "  CLIQUE EM OK! "
	STRING "                "
TABLE 4
;««««««««««««««««««««««««««««««««««««
;	DATA_BASE
;»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»»
PLACE 25D0H
AVEIA:
	STRING "AVEIA;"
	WORD 11
	WORD 56
	WORD 7
PLACE 25E0H
	STRING "PAO FORMA;"
	WORD 9
	WORD 42
	WORD 3
PLACE 25F0H
	STRING "BATATA;"
	WORD 3
	WORD 19
	WORD 0
PLACE 2600H
	STRING "ARROZ;"
	WORD 7
	WORD 25
	WORD 0
PLACE 2610H
	STRING "FEIJAO;"
	WORD 10
	WORD 13
	WORD 0
PLACE 2610H


	STRING "LEGUMES;"
	WORD 3
	WORD 7
	WORD 0
PLACE 2620H
TOMATE:
	STRING "TOMATE;"
    WORD 1
	WORD 3
	WORD 0
PLACE 2630H
BANANA:
	STRING "BANANA;"
    WORD 1 
	WORD 23
	WORD 0
PLACE 2640H
LARANJA:
    STRING "LARANJA;"
    WORD 1 
	WORD 12
	WORD 0
PLACE 2650H
MACA:
	STRING "MACA;"
    WORD 1
	WORD 14
	WORD 0
PLACE 2660H
KIWI:
	STRING "KIWI;"
    WORD 1 
	WORD 15
	WORD 0H
PLACE 2670H
BOLACHA_CHOC:
	STRING "BOLACHA CHOC;"
    WORD 9
	WORD 59
	WORD 22
PLACE 2680H
PIZZA:
	STRING "PIZZA;"
    WORD 13
	WORD 25
	WORD 9
PLACE 2690H
AMENDOAS:
	STRING "AMENDOAS;"
    WORD 26
	WORD 6 
	WORD 55 
PLACE 26A0H
LINHACA:
	STRING "LINHACA;"
    WORD 18 
	WORD 34
	WORD 36
PLACE 26B0H
AZEITE:
	STRING "AZEITE;"
    WORD 0
	WORD 0
	WORD 100
PLACE 26C0H
LEITE_MAGRO:
	STRING "LEITE MAGRO;"
    WORD 3
	WORD 4
	WORD 0
PLACE 26D0H
WHEY:
	STRING "WHEY;"
    WORD 80
	WORD 8
	WORD 4
PLACE 26E0H
SALMAO:
	STRING "SALMAO;"
    WORD 21
	WORD 0
	WORD 15
PLACE 26F0H
PESCADA:
	STRING "PESCADA;"
    WORD 20
	WORD 0 
	WORD 1
PLACE 2700H
ATUM:
	STRING "ATUM;"
    WORD  25
	WORD 0 
	WORD 2
PLACE 2710H
PORCO:
	STRING "PORCO;"
    WORD 22
	WORD 0
	WORD 15
PLACE 2720H
FRANGO:
	STRING "FRANGO;"
    WORD 25
	WORD 0 
	WORD 4
PLACE 2730H
PERU:
	STRING "PERU;"
    WORD 28
	WORD 0 
	WORD 1
PLACE 2740H
OVO:
	STRING "OVO;"
    WORD 7 
	WORD 0
	WORD 5
PLACE 2750H
QUEIJO:
	STRING "QUEIJO;"
    WORD 28
	WORD 0
	WORD 13
	
PLACE 0000H
INICIO: ; INICIALIZA VARIAVEIS E ROTINAS CHAVE
	
	MOV R0, BTN_ON_OFF
	MOVB R0, [R0]	
	MOV R1, SEL_NR_MENU
	MOV R2, BTN_OK
	MOV R3, BTN_CHANGE
	MOV R4, PESO
	
	
	CALLF LIMPADISPLAY	
	CALLF MOSTRA_ESTADO
	
	JMP ATUALIZA
	

ATUALIZA: ;VERIFICA TODOS OS PERIFERICOS CRITICOS E ATUALIZA
	CALL ATUALIZA_BTN_ON_OFF
	CALL LER_BTN_OK
	CALL MENU2_BTN_CHANGE
	CALL MENU2_BTN_GRAVAR
	CALL MENU2_LER_BTN
	CALL MENU1_ADD_2
	JMP ATUALIZA
	
ATUALIZA_BTN_ON_OFF: ;VERIFICA O BTN_ON_OFF E LIGA OU DESLIGA A AMQUINA ATRAVES DOS ESTADOS
	PUSH R1
	MOV R1, BTN_ON_OFF
	MOVB R1, [R1]	
	CMP R1, R0
	JNE ON_OFF
	POP R1
	RET
ON_OFF:
	MOV R0, BTN_ON_OFF
	MOVB R0, [R0]
	POP R1
	PUSH R0
	PUSH R1
	MOV R0, BTN_ON_OFF
	MOVB R0, [R0]
	MOV R1, 58H
	CMP R0, R1
	JNZ OFF
	MOV R0, ESTADO
	MOV R1, 4FH
	MOV R2, 4EH
	MOVB [R0], R1
	ADD R0, 1
	MOVB [R0], R2
	ADD R0,1
	MOV R1, 20H
	MOVB [R0], R1
	MOV R10, MENU_1 ;METER UM CASE AQUI PARA OUTROS MENUS
	CALLF MOSTRADISPLAY
	POP R1
	POP R0
	RET
OFF:
	POP R1
	POP R0
	PUSH R0
	PUSH R1
	MOV R0, ESTADO
	MOV R1, 4FH
	MOVB [R0], R1
	ADD R0, 1
	MOV R1, 46H
	MOVB [R0], R1
	ADD R0, 1
	MOV R1, 46H
	MOVB [R0], R1
	MOV R0, BTN_ON_OFF
	MOV R1, 20H
	MOVB [R0], R1
	CALLF LIMPADISPLAY
	
	POP R1
	POP R0
	RET

MOSTRA_ESTADO: ;INDICA QUAL O ESTADO ATUAL DA MAQUINA
	PUSH R0
	PUSH R1
	PUSH R2
	PUSH R3
	MOV R0, PERIFERICOS
	MOV R2, ESTADO_DA_MAQUINA
CICLO_ESTADO:
	MOVB R3, [R2]
	MOVB [R0], R3
	ADD R0, 1
	ADD R2, 1
	CMP R3, 0
	JNZ CICLO_ESTADO
	POP R3
	POP R2
	POP R1
	POP R0
	RETF

MOSTRADISPLAY: ;TRANSCREVE PARA O ECRA DETERMINADO CONJUNTO DE BITS
	PUSH R0
	PUSH R2
	PUSH R3
	MOV R2, R10
	MOV R0, DISPLAY
CICLO_MOSTRA:
	MOVB R3, [R2]
	MOVB [R0], R3
	ADD R0, 1
	ADD R2, 1
	CMP R3, 0
	JNZ CICLO_MOSTRA
	POP R3
	POP R2
	POP R0
	RETF
	
MOSTRA_ALIMENTO: ; TRANSCREVE O NOME DO ALIMENTO ESCOLHIDO PARA O MENU_PESAGEM
	PUSH R0
	PUSH R1
	PUSH R2
	PUSH R3
	PUSH R4
	PUSH R5
	MOV R5,0
	MOV R4, 03BH
	MOV R2, R8
	MOV R0, DISPLAY_ALIMENTOS
	MOV R1, DISPLAYEND
CICLO_MOSTRA_ALIMENTO:
	MOVB R3, [R2]
	MOVB [R0], R3
	ADD R0, 1
	ADD R2, 1
	MOVB R3, [R2]
	CMP R3, R4
	JNZ CICLO_MOSTRA_ALIMENTO
	POP R5
	POP R4
	POP R3
	POP R2
	POP R1
	POP R0
	RETF
	
LIMPADISPLAY: ;LIMPA O DISPLAY ATRAVES DO CHR 20H
	PUSH R0
	PUSH R1
	PUSH R2
	MOV R0, DISPLAY
	MOV R1, DISPLAYEND
	MOV R2, CARACTERVAZIO
CICLO_LIMPA:
	MOVB [R0], R2
	ADD R0, 1
	CMP R0, R1
	JLE CICLO_LIMPA
	POP R2
	POP R1
	POP R0
	RETF
	
LER_SEL_NR_MENU: ;LE O SELETOR E CONV PARA HEX
	PUSH R0
	PUSH R1
	PUSH R2
	PUSH R3
	PUSH R4

	CALL ENTRE_0_9
	
	POP R4
	POP R3
	POP R2
	POP R1
	POP R0
	RET

ENTRE_0_9:
	
	MOV R0, SEL_NR_MENU
	MOVB R0, [R0]
	MOV R1, 30H ;MINIMO-1
	MOV R2, 39H ;MAXIMO
	
	CMP R0,R1
	JLT ERRO_SEL_NR_MENU; R0 < R1
	CMP R0,R2
	JGT ERRO_SEL_NR_MENU; R0 > R2
	
	MOV R0, SEL_NR_MENU ;PROXIMO CHR
	ADD R0, 1
	MOVB R0, [R0]
	CMP R0,R1
	JLT ERRO_SEL_NR_MENU; R0 < R1
	CMP R0,R2
	JGT ERRO_SEL_NR_MENU; R0 > R2
	RET
ERRO_SEL_NR_MENU:
	PUSH R0
	PUSH R1
	PUSH R6
	MOV R6,MENUERRO
	CMP R6, R10
	JEQ ERRO_SEL_NR_MENU_FIM
	MOV R10, MENUERRO
	CALLF LIMPADISPLAY
	CALLF MOSTRADISPLAY
	CALL LER_BTN_OK
ERRO_SEL_NR_MENU_FIM:
	MOV R1, CARACTERVAZIO
	MOV R0, BTN_OK
	MOVB [R0], R1
	POP R6
	POP R1
	POP R0
	RET  

LER_BTN_OK: ;LE O PERIFERICO OK E AVANCA OU NAO PARA A LEITURA DE OPCAO
	PUSH R0
	PUSH R1
	MOV R0, BTN_OK
	MOVB R0, [R0]
	MOV R1, 58H
	CMP R0, R1
	JNE LER_BTN_OK_FIM
	CALL LE_OPCAO

LER_BTN_OK_FIM: 
	MOV R1, CARACTERVAZIO
	MOV R0, BTN_OK
	MOVB [R0], R1
	
	POP R1
	POP	R0
	RET
	
LE_OPCAO: ;VERIFICA QUAL A OPCAO PARA A SELECAO ESCOLHIDA
	PUSH R0 ; SELETOR
	PUSH R1
	PUSH R2
	PUSH R3
	PUSH R4
	PUSH R5
	PUSH R6
	PUSH R7
	
	; ------ SELETOR------
	MOV R0, SEL_NR_MENU
	CALL SEL_TO_HEX
	;---------------------
	
	MOV R4, MENU_1
	CMP R4, R10
	JEQ MENU1
	
	MOV R4, MENU_ALIMENTOS
	CMP R4, R10
	JEQ MENU2_CHANGE
	
	MOV R4, MENU_GRAVADO
	CMP R4, R10
	JEQ MUNU_INICIO
	
	MOV R4, MENUERRO
	CMP R4, R10
	JEQ MUNU_INICIO
	
	MOV R4, MENU_TOTAL
	CMP R4, R10
	JEQ MUNU_INICIO
	
	MOV R4, MENUERRO_PESAGEM
	CMP R4, R10
	JEQ MENU2_ERRO_PESAGEM
	JMP MENU2_FIM
	
	MUNU_INICIO:
		MOV R0, DISPLAY
		MOV R10, MENU_1
		CALLF LIMPADISPLAY
		CALLF MOSTRADISPLAY	
		JMP MENU2_FIM
	MENU1:
		CMP R0, 1
		JEQ MENU1_1
		CMP R0, 2
		JEQ MENU1_2
		CMP R0, 3
		JEQ MENU1_3
		CMP R0, 4
		JEQ MENU1_ADD
		JMP MENU1_ERRO
	MENU1_1:
		CALL ROTINA_USAR_BALANCA	
		JMP MENU2_FIM
	MENU1_2:
		MOV R0, DISPLAY
		MOV R10, MENU_TOTAL
		CALLF LIMPADISPLAY
		CALLF MOSTRADISPLAY	
		
		MOV R0, BD_PROTEINA
		MOV R5, DISPLAY_PROTEINA_TOTAL
		CALLF HEX_TO_ASCII
		
		MOV R0, BD_CARBONO
		MOV R5, DISPLAY_HIDRATOS_TOTAL
		CALLF HEX_TO_ASCII
		
		MOV R0, BD_GORDURA
		MOV R5, DISPLAY_GORDURA_TOTAL
		CALLF HEX_TO_ASCII
		
		MOV R0, BD_KCAL_SUM
		MOV R5, DISPLAY_KCAL_TOTAL
		CALLF HEX_TO_ASCII
		
		JMP MENU2_FIM
		
	MENU1_3:
		
		PUSH R0
		PUSH R1
		
		MOV R0, TOTAL_CARBONO
		MOVB [R0], R1
		ADD R0,1
		MOVB [R0], R1
		
		MOV R0, TOTAL_PROTEINA
		MOVB [R0], R1
		ADD R0,1
		MOVB [R0], R1
		
		MOV R0, TOTAL_GORDURA
		MOVB [R0], R1
		ADD R0,1
		MOVB [R0], R1
		
		POP R1
		POP R0
		
		JMP MENU2_FIM
	MENU1_ADD:
		MOV R0, DISPLAY
		MOV R10, MENU_ADD_MENU
		CALLF LIMPADISPLAY
		CALLF MOSTRADISPLAY	
		
		JMP MENU2_FIM
	
	MENU1_ERRO:
		MOV R0, DISPLAY
		MOV R10, MENUERRO
		CALLF LIMPADISPLAY
		CALLF MOSTRADISPLAY	
		JMP MENU2_FIM
	MENU2_PESAGEM:
		CALL ROTINA_USAR_BALANCA
		JMP MENU2_FIM
	
	MENU2_CHANGE:
		MENU2_CASO_X:
			CALL CONTA_NOME
			CMP R0, R5
			JGT MENU2_CASO_DEFAULT
			CALL ROTINA_AVEIA
			JMP MENU2_FIM
		
		MENU2_CASO_DEFAULT:
			JMP MENU2_FIM
	
	MENU2_ERRO_PESAGEM:
		JMP MENU2_PESAGEM
		
			
		MENU2_FIM:
			
			MOV R0, SEL_NR_MENU
			MOV R7, 0
			MOVB [R0],R7
			ADD R0, 1
			MOVB [R0],R7
			
			POP R7
			POP R6
			POP R5
			POP R4
			POP R3
			POP R2
			POP R1
			POP R0
			RET


ROTINA_USAR_BALANCA: ;VERIFICA SE FOI ESCOLHIDO UM ALIMENTO E SE N FOR TRANSCREVE TODOS OS ALIMETOS PARA O DISPLAY
		PUSH R0
		MOV R0, DISPLAY_ALIMENTOS
		CMP R6,0
		JZ N_ESCOLHEU
		MOV R10, PESAGEM
		
	N_ESCOLHEU:
		MOV R10, MENU_ALIMENTOS
		CALL MENU
		POP R0
		RET

ROTINA_AVEIA:  ; O ALIMENTO ESCOLHIDO PASSA A SER GRAVADO NUMA BD_TEMP PODENDO SER GRAVADO DEFINITIVAMENTE NO FINAL

	PUSH R6
	MOV R6,R0
	CALL ESCR_BD_TEMP
	POP R6

	PUSH R0
	MOV R0, DISPLAY_ALIMENTOS
	MOV R10, PESAGEM
	CALLF LIMPADISPLAY
	CALLF MOSTRADISPLAY	
	;MOV R8, AVEIA
	MOV R8, BD_NOME
	MOV R8, [R8]
	CALLF MOSTRA_ALIMENTO
	POP R0
	
	RET

ROTINA_DEFAULT:
	

ASCII_TO_HEX: ; CONVERTE DE ASCII PARA HEX
	PUSH R0
	PUSH R1
	PUSH R2 ; 1000
	PUSH R3 ; RESULTADO EM ASCII
	PUSH R4
	PUSH R5 ; 
	PUSH R6
	PUSH R7
	PUSH R8
	
	
	MOV R0, PESO ;ENDERECO DE TESTE
	MOV R1, 30H
	MOV R2, 1000H
	MOV R4, 10H
	MOV R6, 05DH
	MOV R9, 0H
	
ASCII_TO_HEX_REPETIR:
	MOVB R3,[R0]
	
	CALL ASCII_TO_HEX_ENTRE_0_9
	CMP R8,1
	JEQ ASCII_TO_HEX_FIM
	SUB R3, R1
	MUL R3, R2
	ADD R9, R3
	DIV R2, R4
	
	ADD R0, 1
	MOVB R7,[R0]
	CMP R7,R6
	JEQ ASCII_TO_HEX_FIM
	JMP ASCII_TO_HEX_REPETIR
	

ASCII_TO_HEX_ENTRE_0_9:
	PUSH R1
	PUSH R2
	
	MOV R1, 30H ;MINIMO-1
	MOV R2, 39H ;MAXIMO

	CMP R3,R1
	JLT ASCII_TO_HEX_ERROR; R0 < R1
	CMP R3,R2
	JGT ASCII_TO_HEX_ERROR; R0 > R2
	
	POP R2
	POP R1
	MOV R8, 0
	
	RET
	
ASCII_TO_HEX_ERROR:
	
	MOV R10, MENUERRO_PESAGEM
	CALLF LIMPADISPLAY
	CALLF MOSTRADISPLAY
	
	POP R2
	POP R1
	MOV R8,1
	RET

ASCII_TO_HEX_FIM:

	POP R8
	POP R7
	POP R6
	POP R5
	POP R4
	POP R3
	POP R2
	POP R1
	POP R0
	RET
	
MENU2_BTN_CHANGE: ;VERIFICA SE O BTN_CHANGE ESTA ACIONADO SE ESTIVER MUDA PARA O MENU DE ALIMENTOS GERAL
	PUSH R0
	PUSH R1
	MOV R1, 58H
	MOV R0, PESAGEM
	
	CMP R0,R10
	JNE MENU2_BTN_CHANGE_FIM
	MOV R0, BTN_CHANGE
	MOVB R0, [R0]
	CMP R1, R0
	JNE MENU2_BTN_CHANGE_FIM
	MOV R10, MENU_ALIMENTOS
	CALLF LIMPADISPLAY
	CALLF MOSTRADISPLAY
MENU2_BTN_CHANGE_FIM:	
	POP R1
	POP R0
	RET

MENU2_BTN_GRAVAR_EXC_ERRO:
	MOV R10, MENUERRO_PESAGEM
	CALLF LIMPADISPLAY
	CALLF MOSTRADISPLAY
	JMP MENU2_BTN_GRAVAR_FIM
MENU2_BTN_GRAVAR: ; VERIFICA SE O BTN_GRAVAR ESTA ACIONADO SE ESTIVER PASSA PARA A ROTINA DE GRAVACAO
	PUSH R0
	PUSH R1
	PUSH R2
	PUSH R3
	PUSH R4
	PUSH R5
	
	MOV R1, 58H
	MOV R0, PESAGEM
	MOV R3, 3000
	
	CMP R0,R10
	JNE MENU2_BTN_GRAVAR_FIM
	
	
	MOV R0, BTN_GRAVAR
	MOVB R0, [R0]
	CMP R1, R0
	JNE MENU2_BTN_GRAVAR_FIM
	CALL ASCII_TO_HEX
	CALL DEC_TO_HEX_PESO

	CMP R9, R3
	JGT MENU2_BTN_GRAVAR_EXC_ERRO ; SE FOR MAIS DE 3000G
	MOV R10, MENU2_GRAVAR
	CALLF LIMPADISPLAY
	CALLF MOSTRADISPLAY
	
	
	
	MOV R1, 100H
	MOV R5, R9
	DIV R5, R1
	
	CALLF MUL_NUTR
	CALLF KCAL_SUM
	CALL MENU2_BTN_GRAVAR_MUL_WR
	
	;------------------------------

	JMP MENU2_BTN_GRAVAR_FIM

MENU2_BTN_GRAVAR_FIM:
	POP R4
	POP R4	
	POP R3
	POP R2
	POP R1
	POP R0
	RET
	
DEC_TO_HEX_PESO: ; TRANSCREVE O PESO E DECIMAL PARA HEX
	PUSH R0
	PUSH R1 ; 16
	PUSH R2 ; BIT
	PUSH R3 ; RESTO
	PUSH R4
	PUSH R5
	PUSH R6
	PUSH R7
	PUSH R8
	
	MOV R9, PESO
	
	MOV R5,0
	MOV R1,3E8H
	MOV R2,064H
	MOV R3,00AH
	MOV R4,1
	MOV R6,30H
	
	MOVB R0, [R9]
	MOV R7,BD_PESO
	MOVB [R7],R0
	SUB R0 ,R6 
	MUL R0,R1
	ADD R5, R0
	
	ADD R9, 1
	MOVB R0, [R9]
	MOV R7,BD_PESO
	ADD R7,1
	MOVB [R7],R0
	SUB R0 ,R6 
	MUL R0,R2
	ADD R5, R0
	
	ADD R9, 1
	MOVB R0, [R9]
	MOV R7,BD_PESO
	ADD R7,2
	MOVB [R7],R0
	SUB R0 ,R6
	MUL R0,R3
	ADD R5, R0
	
	ADD R9, 1
	MOVB R0, [R9]
	MOV R7,BD_PESO
	ADD R7,3
	MOVB [R7],R0
	SUB R0 ,R6 
	MUL R0,R4
	ADD R5, R0
	
	MOV R7, BD_PESO_HEX
	MOV [R7], R5

DEC_TO_HEX_FIM:	
	
	MOV R9,R5
	
	POP R8
	POP R7
	POP R6
	POP R5
	POP R4
	POP R3
	POP R2
	POP R1
	POP R0
	RET
	
HEX_TO_DEC: ;PASSA DE HEX PARA DEC

	PUSH R0
	PUSH R1
	PUSH R2
	PUSH R3
	PUSH R4
	
	MOV R0, 176d
	MOV R1, 8d
	
	ADD R0,R1
	
	POP R4
	POP R3
	POP R2
	POP R1
	POP R0
	RET


MENU2_BTN_GRAVAR_MUL_WR: ;GRAVA EM CERTOS ENDERECOS DETERMINADOS VALORES CORRESPONDENTES AO ALIMENTO ESCOLHIDO 

	PUSH R0
	PUSH R1
	PUSH R2
	PUSH R3
	PUSH R4
	PUSH R5
	PUSH R6
	PUSH R10
	
	MOV R10, BD_NOME
	MOV R10, [R10]
	MOV R0, DISPLAY_NOME_GRAVAR
	CALLF MENU2_BTN_GRAVAR_MOSTRADISPLAY
	
	MOV R10, BD_PESO
	MOV R0, DISPLAY_PESO_GRAVAR
	CALLF MENU2_BTN_GRAVAR_MOSTRADISPLAY
	
	MOV R0, BD_PROTEINA
	MOV R5, DISPLAY_PROTEINA_GRAVAR
	CALLF HEX_TO_ASCII
	
	MOV R0, BD_CARBONO
	MOV R5, DISPLAY_HIDRATOS_GRAVAR
	CALLF HEX_TO_ASCII
	
	MOV R0, BD_GORDURA
	MOV R5, DISPLAY_GORDURA_GRAVAR
	CALLF HEX_TO_ASCII
	
	MOV R0, BD_KCAL_SUM
	MOV R5, DISPLAY_KCAL_GRAVAR
	CALLF HEX_TO_ASCII
	
		;----
	
	MOV R0, TOTAL_PROTEINA
	MOV R6, BD_PROTEINA
	MOV R0, [R0]
	MOV R6, [R6]
	ADD R0, R6
	MOV R5, DISPLAY_PROTEINA_GRAVAR_TOTAL
	CALLF HEX_TO_ASCII_2
	
	MOV R0, TOTAL_CARBONO
	MOV R6, BD_CARBONO
	MOV R0, [R0]
	MOV R6, [R6]
	ADD R0, R6
	MOV R5, DISPLAY_HIDRATOS_GRAVAR_TOTAL
	CALLF HEX_TO_ASCII_2
	
	MOV R0, TOTAL_GORDURA
	MOV R6, BD_GORDURA
	MOV R0, [R0]
	MOV R6, [R6]
	ADD R0, R6
	MOV R5, DISPLAY_GORDURA_GRAVAR_TOTAL
	CALLF HEX_TO_ASCII_2
	
	MOV R0, TOTAL_KCAL_SUM
	MOV R6, BD_KCAL_SUM
	MOV R0, [R0]
	MOV R6, [R6]
	ADD R0, R6
	MOV R5, DISPLAY_KCAL_GRAVAR_TOTAL
	CALLF HEX_TO_ASCII_2

	POP R10
	POP R6
	POP R5
	POP R4
	POP R3
	POP R2
	POP R1
	POP R0
	RET

MENU2_BTN_GRAVAR_MOSTRADISPLAY:
	PUSH R2
	PUSH R3
	PUSH R4
	MOV R2, R10
MENU2_BTN_GRAVAR_CICLO_MOSTRA:
	MOVB R3, [R2]
	CMP R3, 0
	JEQ MENU2_BTN_GRAVAR_CICLO_MOSTRA_FIM
	MOVB [R0], R3
	ADD R0, 1
	ADD R2, 1
	CMP R3, 0
	JNZ MENU2_BTN_GRAVAR_CICLO_MOSTRA
MENU2_BTN_GRAVAR_CICLO_MOSTRA_FIM:
	POP R4
	POP R3
	POP R2
	RETF
	
MENU2_BTN_GRAVAR_MOSTRADISPLAY_ASCII:
	PUSH R1
	PUSH R2
	PUSH R3
	PUSH R4
	PUSH R5
	PUSH R6
	PUSH R7
	PUSH R8
	PUSH R9

MENU2_BTN_GRAVAR_CICLO_MOSTRA_ASCII:

	MOV R2, R10
	MOV R1, 10H
	MOV R5, 9
	MOV R6, 10
	
	MOV R9,0
	MOVB R3, [R2]
	MOV R8, R3
	CMP R3, 0
	JEQ MENU2_BTN_GRAVAR_CICLO_MOSTRA_FIM_ASCII
	DIV R3, R1
	CMP R3, R5
	JLE MENU2_BTN_GRAVAR_CICLO_MOSTRA_ASCII_30
	JMP MENU2_BTN_GRAVAR_CICLO_MOSTRA_ASCII_37
	
MENU2_BTN_GRAVAR_CICLO_MOSTRA_ASCII_30:
	MOV R7, 30H
	ADD R3, R7
	CMP R9,1
	JEQ MENU2_BTN_GRAVAR_CICLO_MOSTRA_ASCII
	JMP MENU2_BTN_GRAVAR_CICLO_MOSTRA_SEG
MENU2_BTN_GRAVAR_CICLO_MOSTRA_ASCII_37:
	MOV R7, 30H
	ADD R7, 7
	ADD R3, R7
	CMP R9,1
	JEQ MENU2_BTN_GRAVAR_CICLO_MOSTRA_ASCII_REPETIR
	JMP MENU2_BTN_GRAVAR_CICLO_MOSTRA_SEG	
	
MENU2_BTN_GRAVAR_CICLO_MOSTRA_SEG:

	MOVB [R0], R3 ;ESCREVER R3 NO R0
	ADD R0, 1
	
	MUL R3, R1
	SUB R8, R3
	
	MOV R3, R8
	MOV R9,1
	CMP R5, R3
	JLE MENU2_BTN_GRAVAR_CICLO_MOSTRA_ASCII_30
	JMP MENU2_BTN_GRAVAR_CICLO_MOSTRA_ASCII_37
	
MENU2_BTN_GRAVAR_CICLO_MOSTRA_ASCII_REPETIR:	

	ADD R2, 1
	JMP MENU2_BTN_GRAVAR_CICLO_MOSTRA_ASCII
MENU2_BTN_GRAVAR_CICLO_MOSTRA_FIM_ASCII:
	
	POP R9
	POP R8
	POP R7
	POP R6
	POP R5
	POP R4
	POP R3
	POP R2
	POP R1
	RETF
	


MUL_NUTR:

	PUSH R0
	PUSH R1
	PUSH R2
	PUSH R3
	
	MOV R0, 100
	MOV R1, BD_PESO_HEX
	MOV R1,[R1]
	DIV R1,R0 
	
	;REGRA 3 SIMP -- PROTEINA
	MOV R2, BD_PROTEINA
	MOVB R2, [R2]
	MUL R2, R1
	MOV R3, BD_PROTEINA
	MOV [R3],R2 
	
	;REGRA 3 SIMP -- Hidratos Carbono
	MOV R2, BD_CARBONO
	MOVB R2, [R2]
	MUL R2, R1
	MOV R3, BD_CARBONO
	MOV [R3],R2 
	
	;REGRA 3 SIMP -- Gordura
	MOV R2, BD_GORDURA
	MOVB R2, [R2]
	MUL R2, R1
	MOV R3, BD_GORDURA
	MOV [R3],R2 
	
	POP R3
	POP R2
	POP R1
	POP R0
	RETF
	
KCAL_SUM:
	PUSH R0
	PUSH R1
	PUSH R2
	PUSH R3
	PUSH R4
	
	MOV R0, BD_CARBONO
	MOV R1, BD_GORDURA
	MOV R2, BD_PROTEINA
	MOV R3, BD_KCAL_SUM
	MOV R4, 0
	
	MOV R0, [R0]
	MOV R1, [R1]
	MOV R2, [R2]
	
	ADD R4, R0
	ADD R4, R1
	ADD R4, R2
	
	MOV [R3], R4
	
	POP R4
	POP R3
	POP R2
	POP R1
	POP R0
	RETF

HEX_TO_ASCII:
	
	PUSH R1
	PUSH R2
	PUSH R3
	PUSH R4
	PUSH R6
	PUSH R7
	MOV R2, 10
	MOV R3, 1000H
	MOV R4, 10H
HEX_TO_ASCII_BYT_1:	

	MOV R6, [R0]
	DIV R6, R3
	CALL HEX_TO_ASCII_CONV
	MOVB [R5], R6

	MOV R6, [R0]
	DIV R6, R3
	MUL R6, R3
	MOV R7, [R0]
	SUB R7,R6
	DIV R3,R4
	DIV R7, R3	
	MOV R6,R7
	CALL HEX_TO_ASCII_CONV
	ADD R5,1
	MOVB [R5], R6

HEX_TO_ASCII_BYT_2:	

	MOV R6, [R0]
	MOV R7, [R0]
	DIV R6, R3
	MUL R6, R4
	MUL R6, R4
	SUB R7, R6
	MOV R0, R7
	DIV R7, R4
	ADD R5,1
	MOV R6, R7
	CALL HEX_TO_ASCII_CONV
	MOVB [R5], R6
	MUL R7, R4
	SUB R0, R7
	MOV R6, R0
	ADD R5,1
	CALL HEX_TO_ASCII_CONV
	MOVB [R5], R6

HEX_TO_ASCII_FIM:
	POP R7
	POP R6
 	POP R4
	POP R3
	POP R2
	POP R1
	RETF
	
HEX_TO_ASCII_CONV:
	PUSH R0
	PUSH R1
	PUSH R2
	MOV R0, 30H
	MOV R1, 9
	MOV R2, 37H
	
	CMP R6, R1
	JLE ADD_30
	ADD R6, R2
	POP R2
	POP R1
	POP R0
	RET
ADD_30:	
	ADD R6, R0
	POP R2
	POP R1
	POP R0
	RET
	
MENU2_LER_BTN:
	
	PUSH R0
	PUSH R1
	PUSH R2
	PUSH R3
	
	MOV R0, BTN_SIM
	MOVB R1, [R0]
	MOV R3, 58H
	CMP R1, R3
	JEQ MENU2_LER_BTN_SIM
	MOV R3, 0
	MOVB [R0], R3
	JMP MENU2_LER_BTN_FIM
	
	MOV R0, BTN_NAO
	MOVB R1, [R0]
	MOV R3, 58H
	CMP R1, R3
	JEQ MENU2_LER_BTN_NAO
	MOV R3, 0
	MOVB [R0], R3
	JMP MENU2_LER_BTN_FIM
	
MENU2_LER_BTN_SIM:
	
	PUSH R0
	PUSH R5
	
	MOV R0, BD_PROTEINA
	MOV R5, TOTAL_PROTEINA
	MOV R0, [R0]
	MOV [R5],R0
	
	MOV R0, BD_CARBONO
	MOV R5, TOTAL_CARBONO
	MOV R0, [R0]
	MOV [R5],R0
	
	MOV R0, BD_GORDURA
	MOV R5, TOTAL_GORDURA
	MOV R0, [R0]
	MOV [R5],R0
	
	MOV R10, MENU_GRAVADO
	CALLF LIMPADISPLAY
	CALLF MOSTRADISPLAY
	
	POP R5
	POP R0
	
	JMP MENU2_LER_BTN_FIM
	
MENU2_LER_BTN_NAO:
	MOV R10, MENU_1
	CALLF LIMPADISPLAY
	CALLF MOSTRADISPLAY
	
	JMP MENU2_LER_BTN_FIM
	
MENU2_LER_BTN_FIM:	
	POP R3
	POP R2
	POP R1
	POP R0
	RET

CONTA_NOME:
	
	PUSH R0
	PUSH R1
	PUSH R2
	PUSH R3
	PUSH R4
	
	MOV R2, 10H
	MOV R3,INDICE_PROXIMO
	MOV R4, INDICE_PROXIMO_REG
	MOV R0,AVEIA
	MOV R5,0

	MOV R1,[R0]
	CMP R1, 0
	JEQ CONTA_NOME_REPETIR
CONTA_NOME_REPETIR:
	ADD R5,1
	ADD R0,R2
	MOV R1,[R0]
	CMP R1, 0
	JNE CONTA_NOME_REPETIR
CONTA_NOME_FIM:
	POP R4
	POP R3
	POP R2
	POP R1
	POP R0
	RET
	
ADD_DB:
	PUSH R1
	PUSH R2
	PUSH R3
	PUSH R4
	
	MOV R2, 10H
	MOV R3,INDICE_PROXIMO
	MOV R4, INDICE_PROXIMO_REG
	MOV R0,AVEIA
	MOV R5,0

	MOV R1,[R0]
	CMP R1, 0
	JEQ ADD_DB_REPETIR
ADD_DB_REPETIR:
	ADD R5,1
	ADD R0,R2
	MOV R1,[R0]
	CMP R1, 0
	JNE ADD_DB_REPETIR
ADD_DB_FIM:
	POP R4
	POP R3
	POP R2
	POP R1
	RET
	
MENU:
	PUSH R0
	PUSH R1
	PUSH R2
	PUSH R3
	PUSH R4
	PUSH R5
	PUSH R6
	PUSH R7
	PUSH R10
	
	MOV R10, MENU_ALIMENTOS ;METER UM CASE AQUI PARA OUTROS MENUS
	CALLF MOSTRADISPLAY
	
	
	MOV R0, DISPLAY
	MOV R10, AVEIA
	MOV R2, 10H
	
	MOV R9,39H
	MOV R1,30H
	MOV R5,30H
	MOV R7,2DH
	ADD R0, R5 
	ADD R0,3

	
MENU_REPETIR:
	

	CALLF MOSTRADISPLAY_MENU
	CALL MENU_CONTA
	ADD R10, R2
	ADD R0,R2
	MOVB R6, [R10]
	CMP R6, 0
	JNE MENU_REPETIR
	
MENU_FIM:
	POP R10
	POP R7
	POP R6
	POP R5
	POP R4
	POP R3
	POP R2
	POP R1
	POP R0
	RET
	
MOSTRADISPLAY_MENU:
	PUSH R0
	PUSH R2
	PUSH R3
	PUSH R4
	
	MOV R2, R10

	MOV R4, 3BH
	
CICLO_MOSTRA_MENU:
	MOVB R3, [R2]
	MOVB [R0], R3
	ADD R0, 1
	ADD R2, 1
	MOVB R3, [R2]
	CMP R3, R4
	JNZ CICLO_MOSTRA_MENU
	
	POP R4
	POP R3
	POP R2
	POP R0
	RETF

MENU_CONTA:
	PUSH R9

	SUB R0,3
	
	MOVB [R0],R1
	
	ADD R0,1
	ADD R5,1
	CMP R5,R9
	JGT MENU_CONTA_0_9
	MOVB [R0], R5 
	
	ADD R0,1
	MOVB [R0], R7
	ADD R0,1
	
MENU_CONTA_FIM:
	POP R9
	RET

MENU_CONTA_0_9:
	PUSH R6
	MOV R6, 30H
	
	SUB R0,1
	
	ADD R1,1
	MOVB [R0],R1
	ADD R0,1
	MOV R5,R6
	MOVB [R0], R5
	
	ADD R0,1
	MOVB [R0], R7
	ADD R0,1
	
	POP R6
	JMP MENU_CONTA_FIM
	
SEL_TO_HEX:
	
	PUSH R1
	PUSH R2
	PUSH R3
	PUSH R4
	
	MOV R4, 0AH
	MOV R3, 30H
	
	MOVB R1, [R0]
	SUB  R1, R3
	ADD R0,1
	MOVB R2, [R0]
	SUB  R2, R3
	
	MUL R1,R4
	ADD R1,R2
	MOV R0,R1
	
	POP R4
	POP R3
	POP R2
	POP R1
	RET
	
ESCR_BD_TEMP:
	
	PUSH R0
	PUSH R1
	PUSH R2
	PUSH R3
	PUSH R4
	PUSH R5
	PUSH R10
	
	MOV R2, 10H
	MOV R3,INDICE_PROXIMO
	MOV R4, INDICE_PROXIMO_REG
	MOV R0,AVEIA
	MOV R5,0

	MOV R1,[R0]
	CMP R1, 0
	JEQ ESCR_BD_TEMP_REPETIR
ESCR_BD_TEMP_REPETIR:
	ADD R5,1
	CMP R5, R6
	JEQ ESCR_BD_TEMP_GRAVAR
	ADD R0,R2
	MOV R1,[R0]
	CMP R1, 0
	JNE ESCR_BD_TEMP_REPETIR
ESCR_BD_TEMP_GRAVAR:
	
	MOV R10, BD_NOME
	MOV [R10], R0
	PUSH R1
	PUSH R2
	MOV R1,R0
	CALL ESCR_BD_TEMP_GRAVAR_NEXT
	POP R2
	POP R1

ESCR_BD_TEMP_FIM:
	POP R10
	POP R5
	POP R4
	POP R3
	POP R2
	POP R1
	POP R0
	RET
ESCR_BD_TEMP_GRAVAR_NEXT:
	ADD R1, 1
	MOVB R2, [R1]
	CMP R2, 0
	JNE ESCR_BD_TEMP_GRAVAR_NEXT
ESCR_BD_TEMP_GRAVAR_R1:	
	ADD R1, 1
	MOVB R2, [R1]
	CMP R2, 0
	JEQ ESCR_BD_TEMP_GRAVAR_R1
	MOV R10, BD_PROTEINA
	MOVB [R10], R2
ESCR_BD_TEMP_GRAVAR_R2:	
	ADD R1, 1
	MOVB R2, [R1]
	CMP R2, 0
	JEQ ESCR_BD_TEMP_GRAVAR_R2
	MOV R10, BD_CARBONO
	MOVB [R10], R2
ESCR_BD_TEMP_GRAVAR_R3:		
	ADD R1, 1
	MOVB R2, [R1]
	CMP R2, 0
	JEQ ESCR_BD_TEMP_GRAVAR_R3
	MOV R10, BD_GORDURA
	MOVB [R10], R2
	RET
	
HEX_TO_ASCII_2:
	
	PUSH R1
	PUSH R2
	PUSH R3
	PUSH R4
	PUSH R6
	PUSH R7
	MOV R2, 10
	MOV R3, 1000H
	MOV R4, 10H
HEX_TO_ASCII_2_BYT_1:	

	MOV R6, R0
	DIV R6, R3
	CALL HEX_TO_ASCII_CONV
	MOVB [R5], R6

	MOV R6, R0
	DIV R6, R3
	MUL R6, R3
	MOV R7, R0
	SUB R7,R6
	DIV R3,R4
	DIV R7, R3	
	MOV R6,R7
	CALL HEX_TO_ASCII_CONV
	ADD R5,1
	MOVB [R5], R6

HEX_TO_ASCII_BYT_2_2:	

	MOV R6, R0
	MOV R7, R0
	DIV R6, R3
	MUL R6, R4
	MUL R6, R4
	SUB R7, R6
	MOV R0, R7
	DIV R7, R4
	ADD R5,1
	MOV R6, R7
	CALL HEX_TO_ASCII_CONV
	MOVB [R5], R6
	MUL R7, R4
	SUB R0, R7
	MOV R6, R0
	ADD R5,1
	CALL HEX_TO_ASCII_CONV
	MOVB [R5], R6

HEX_TO_ASCII_2_FIM:
	POP R7
	POP R6
 	POP R4
	POP R3
	POP R2
	POP R1
	RETF
	
MENU1_ADD_2:
	PUSH R1
	PUSH R2
	
	MOV R1, MENU_ADD_MENU
	CMP R10, R1
	JNE MENU1_ADD_2_FIM
	
	MOV R1, 0C6BH
	MOV R2, 58H
	MOVB R1, [R1]
	CMP R1,R2
	JNE MENU1_ADD_2_FIM
	
	
	CALL ADD_DB
	MOV R10, 0BB1H
	CALL MENU1_ADD_INS
	
MENU1_ADD_2_FIM:	
	POP R2
	POP R1
	RET
	
MENU1_ADD_INS:
	PUSH R1
	PUSH R2
	PUSH R3
	MOV R3, 20H
MENU1_ADD_CICLO:
	MOVB R1, [R10]
	CMP R1,R3
	JEQ MENU1_ADD_FIM
	MOVB [R0], R1
	ADD R10, 1
	ADD R0,1
	JMP MENU1_ADD_CICLO
MENU1_ADD_FIM:
	POP R3
	POP R2
	POP R1
	RET